<?xml version="1.0" encoding="utf-8"?><Database Name="modulo2" Class="EntidadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-54IKPVH;Initial Catalog=modulo2;Integrated Security=True" SettingsObjectName="Modelo.Properties.Settings" SettingsPropertyName="modulo2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.alimentos" Member="alimentos">
    <Type Name="alimentos">
      <Column Name="idAlimentos" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="idTipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="detalles" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="tipo_alimentos_alimentos" Member="tipo_alimentos" ThisKey="idTipo" OtherKey="idTipo" Type="tipo_alimentos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.chef" Member="chef">
    <Type Name="chef">
      <Column Name="idChef" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="documento" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="clientes">
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="documento" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cocineros" Member="cocineros">
    <Type Name="cocineros">
      <Column Name="idCocineros" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="documento" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="roles">
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreRol" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="roles_usuarios" Member="usuarios" ThisKey="idRol" OtherKey="idRol" Type="usuarios" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_alimentos" Member="tipo_alimentos">
    <Type Name="tipo_alimentos">
      <Column Name="idTipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombretipo" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="tipo_alimentos_alimentos" Member="alimentos" ThisKey="idTipo" OtherKey="idTipo" Type="alimentos" />
    </Type>
  </Table>
  <Table Name="dbo.usuarios" Member="usuarios">
    <Type Name="usuarios">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="roles_usuarios" Member="roles" ThisKey="idRol" OtherKey="idRol" Type="roles" IsForeignKey="true" />
    </Type>
  </Table>
</Database>